### ISSUE TITLE
レポート班の人員確保と分担決め

### ISSUE THREAD

**Issue by Takashi-U** [matsuerb/matrk05#1]
プログラムのページ
https://github.com/matsuerb/matrk05/wiki/Program

**Comment by Takashi-U** [comment]
前回のMatsue.rbで、一つのプログラムで一人がレポートを書くというように、分担をしたら良さそうというideaをいただいています。

恐らくは負担の分担という意味が強いとは思います。
もう一つ、自分自身が前回レポートを担当したのですが、るびまに携わる（るびまに載る）のは良い体験だと思いました。と言うわけで、そういった意味でも幅広く数人が携わるのは良いことだと感じました。

@sho-h 人数的にはどんな感じでしょうか？

**Comment by yoshiokaCB** [comment]
ライブコーディングの枠が3〜4で少し流動的なので、レポートの人数も変動しそうです。
年末までに内容を確定したいと思ってますのでもう少々おまちください。

**Comment by Takashi-U** [comment]
ガッテンです！

いずれにしましてもまだ足りてないと思うので、レポート班立候補の方はこちらに追記してください〜
https://github.com/matsuerb/matrk05/wiki/Roles

**Comment by amidaku** [comment]
少なくとも前々回は、セッション毎に担当を決めて、"きちんと確実に"レポートを残すようにしていたはずです。
支援もいただくので、その方が良いかと思います。
まずは、セッションの確定ですかね。

**Comment by Takashi-U** [comment]
了解です！
セッション確定の後は担当を決めること留意したいと思います。

**Comment by sho-h** [comment]
@Takashi-U Issue作成ありがとうございます！以前のセッション毎の担当は一人の人がずっと気を張ってなくてもいい面もありいい事ずくめだった印象です。兼務可なのもいいですね。確かにセッションの確定が先とは思いますが、上の枠+基調講演+Ruby Jr.(講師の誰かが兼務？)というところで5〜6人くらいですかねぇ。

**Comment by Takashi-U** [comment]
【Issue:プログラムの確定】
https://github.com/matsuerb/matrk05/issues/3

プログラムの決定後の分担についてもこちらのissueで対応したらと思い、タイトルを変更しました。
（タスクとしては切り分けるのが良さそうだとも思いましたが、issue全体の見通しの悪さを嫌ったところです。切り分けた方が良ければ、切り分けましょう。）

**Comment by Takashi-U** [comment]
@tomomura さんにもレポート担当で加わっていただきました。ありがとうございます！

**Comment by sho-h** [comment]
:+1:

**Comment by takaokouji** [comment]
:+1:

**Comment by sho-h** [comment]
@nobyuki さんにもレポート担当に加わってもらいました。教育まわりに興味がある人なので、@takaokouji さんの発表のレポート書いてもらうとおもしろいんじゃないかと思ってお願いして、快くひきうけてもらいました。

**Comment by Takashi-U** [comment]
:+1:

**Comment by yoshiokaCB** [comment]
1/11ミーティングの内容
- レポート
  - あとひとりふたり欲しい。
  - ただし、今いる人数で残ったパートを分担してもいいと思う
  - 一人は外部からお呼びする方について @hnozaka さんにお願いしようかと思った
  - 他にこちらも @yoshiokaCB さんからスタッフに後からお誘いする
  - 参考(るびま): レポートは ruby の会に送って、同じようにるびまに掲載されます
    - http://magazine.rubyist.net/?0040-MatsueRubyKaigi04Report
    - http://magazine.rubyist.net/?0035-MatsueRubyKaigi03Report

**Comment by sho-h** [comment]
各項目に対して @Takashi-U さんと相談して「？」付きの担当のところに候補を挙げてみました。

| 内容 | 担当 |
| --- | --- |
| LT1 | @tomomura さん? |
| LT2 | @shakkun さん |
| LT3 | @Takashi-U さん |
| LT4 | @sho-h |
| LT5 | @sho-h |
| LT6 | @Takashi-U さん |
| 基調講演 | @shakkun さん、@Takashi-U さん |
| Session#01 | n さん |
| Session#02 | @tomomura さん? |
| Session#03 | @shakkun さん? or @Takashi-U さん? |
| Session#04 | @sho-h |
| Session#05 | @nobyuki さん |
| RubyJr | @nobyuki さん |
| 大喜利 | @ToruKurahashi さん |

あとは希望を取らせてもらって入れ替えて fix としたいと思います。？がついていないところもなにか希望がありましたら、言ってくださいませー。> @shakkun さん、@tomomura さん

**Comment by shakkun** [comment]
大丈夫だと思います！( ˆoˆ )

**Comment by sho-h** [comment]
どもですー。@tomomura さんもよかったですか？

**Comment by tomboy67** [comment]
連絡が遅くなってしまい申し訳ありません。
参加出来そうにありません。。

**Comment by sho-h** [comment]
おぉ、了解です。では代案を後で考えますですー。

**Comment by yoshiokaCB** [comment]
人手が足りなければ、私がしましょうか？
LT1はもしかするとバタバタしてる可能性もあるので、難しいですが、session#02ならできそうな気がします。
もしくは誰かに頼みましょうか？

**Comment by sho-h** [comment]
おぉ！お願いしてもいいですか？> @yoshiokaCB  さん
LT1は誰かにお願いしてみます。

**Comment by yoshiokaCB** [comment]
了解しました！
詳細は当日お聞きしますね。

**Comment by Takashi-U** [comment]
https://github.com/matsuerb/matrk05/wiki/Program

とりあえず現状を更新しました。ご確認下さい。
懇親会は勝手に自分にしておきました。

というわけで、LT1が決まればcloseっぽいですね。

**Comment by sho-h** [comment]
@sada くんに LT1 をお願いしたのですが、よく考えたら LT はこれまであまり書いた事ないみたいでしたね...明日の朝ちょっと相談させてくださいませ。> @yoshiokaCB さん、@Takashi-U さん
- http://magazine.rubyist.net/?0040-MatsueRubyKaigi04Report#l11

**Comment by Takashi-U** [comment]
過去の例だとLTはタイトル紹介程度でしたね。というわけで、協議の上LTは内容まで踏み込まない（タイトルの紹介程度）としました。

これで役割が決まりましたのでcloseします。
