### ISSUE TITLE
運営への開催連絡(http://regional.rubykaigi.org/ に予定を載せてもらう)

### ISSUE THREAD

**Issue by sho-h** [matsuerb/matrk05#10]
地域Ruby会議の運営の方々への開催連絡が必要でした。
それと併せて同時にホームページに載せていただく形になったんだったと思います。

前回は @takaokouji さんがやってくれて、今回は @yoshiokaCB さんかな？などと思いつつも、ML に入る必要があるので要相談かもです。前回は以下のような内容を送りました。

```
地域Ruby会議　運営者さま

Matsue.rbの高尾です。

# <ML に橋本を追加するくだりなので省略>

大変ご連絡が遅くなりましたが、2012/9/1(土)に松江Ruby会議04を開催いたします。
オープンソースカンファレンス 2012 Shimane (http://www.ospn.jp/osc2012-shimane/) との同時開催です。
松江Ruby会議04としては、まつもとさんのキーノートと15分間の4コマのみという、とても短いイベントです。

内容としては、Matsue.rbのこれまでの歩みを紹介するといったものです。

レポート係は8/25(土)のMatsue.rb定例会で決める予定です。

--- 下記、事務連絡
- 名称: 松江会議04 (MatsueRubyKaigi04)
- 会期: 2012/09/01(土) 10:00-17:10
- 会場: 松江テルサ (島根県松江市・JR松江駅前)（http://www.sanbg.com/terrsa/access/index.html）
- 参加費: 無料
- 配信: Ustream（http://www.ustream.tv/channel/osc-2012-shimane）
- 懇親会: 18:00-20:00 BISTRO 庵 TENDER (ビストロ アン タンドール) （http://www.ospn.jp/osc2012-shimane/modules/eguide/event.php?eid=1）
- 定員: 150名程度
- 主催: Matsue.rb（高尾宏治、橋本将）

以上です。
よろしくお願いいたします。
```

**Comment by yoshiokaCB** [comment]
@sho-h さん
@takaokouji さんと以前話したときには、Ruby会議運営側とのやり取りは自分がやりますよ的なことを言われていました。ですんで、実際どうするかはおまかせで何も考えておりませんでした。
ちょっと相談してみます。
まぁ、何にせよもう少し詳細を決めないといけませんね。

**Comment by sho-h** [comment]
上記について 12/14 にちょっと口頭で @yoshiokaCB さんと、
- まずはプログラム決める
- 運営さんにメールするのは(ML には入ってるので) @sho-h も対応可能
- メールするの既に ML に入ってる二人のどちらかが楽かも

といった事を相談しました。上のまま @takaokouji さんも対応可だとも思いますし、プログラム決まった時に手が出せる方でいいかな的なところで少し置いておきます。

**Comment by takaokouji** [comment]
橋本さん、ありがとう。
橋本さんがコメントした通りなのですが、できれば運営への連絡は私以外の方（というと橋本さんになるかな？）にお願いできないでしょうか。
気持ち的にも、物理的にも年度末までいろいろたまっており、そんなに動けそうにないという不安があります。(Ruby.JrとRAが...)

すみませんが、よろしくお願いします。

**Comment by sho-h** [comment]
了解ですー。(一個さん付け忘れてたので上の自分のコメントも修正...)

**Comment by takaokouji** [comment]
:+1:

**Comment by sho-h** [comment]
報告しました。(先方の ML の 1171 です)
