### ISSUE TITLE
ライブコーディング大喜利をしてみたい。

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk05#11]
@ToruKurahashi さんから「ライブコーディング大喜利」をプログラムに組み込みたいと言うご提案がありました。
可能かどうか検討中のため、今のところプログラムには組み込んでおりません。
そこで、できれば１月のMatsue.rb定例会の時に実際に試してみてプログラムに組み込めるかどうか検討したいと思っています。
企画の内容説明等は @ToruKurahashi さんから追って説明があるかと思います。また、当日（1月11日）の大喜利の協力者の募集もしております。皆様ご協力をお願いいたします。

**Comment by ToruKurahashi** [comment]
えっと、考えます。

**Comment by yoshiokaCB** [comment]
どうやらRuby Jrの裏（0次会）で開催する方向です。。。

**Comment by inoh** [comment]
今日の大喜利の素振りでわかった課題メモです。
- リアルタイムに更新するためにプロジェクタを映す端末で操作が必要
- プログラムが打っている最中に勝手に書き変わってしまう

**Comment by ToruKurahashi** [comment]
井上さんありがとうございます。他の皆様も何かありましたらここに書いてくださいね。

**Comment by sho-h** [comment]
それぞれの実行結果が表示できるとうれしいと思いましたー。
あと誰が誰だかわかるように gravatar なども表示できる方がおもしろいと思ったんですが、それだとせまくなっちゃうので、微妙なアイディアなのでした。ユーザ名が表示されるから諦めるとかですかねぇ。

**Comment by inoh** [comment]
:+1:

**Comment by yoshiokaCB** [comment]
1/11　ミーティングメモ
- 大喜利
  - スクリーンに 4 分割して表示した画面に各個人の PC から接続、コード編集すると反映
  - これでお題(デモでは 1..50 の和？)を解くことでワイワイやる
  - Ruby Jr. の時間が 2 時間ある
  - Ruby Jr. の観客とどっちにするかは自由
  - デモに関する意見募集中

**Comment by Takashi-U** [comment]
当日の進行関連を承ったところであります。
運営部分についてご意見ある方は、私にリプしてくださいまし。

@yoshiokaCB @ToruKurahashi 
設備面についての問題は大丈夫でしょうか？
念のため確認です。

**Comment by yoshiokaCB** [comment]
@Takashi-U 
諸々整理ありがとう。
設備は @ToruKurahashi さんに確認ですね。
多分当日まで音信不通かもね。。。

**Comment by Takashi-U** [comment]
機材の確認等の実務的な話を、@ToruKurahashi さんの生存確認の流れで、そのままFacebook上で行ってしまいました。

準備等の確認ができたのでcloseします。
@yoshiokaCB @ToruKurahashi 各人、準備物の手配よろしくお願いします！
