### ISSUE TITLE
全体ミーティングのお知らせ

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk05#13]
ご連絡が遅くなりましたが、今週末に全体ミーティングを行います。
ご都合が付く方は、ご参加をお願いいたします。

---

日時：1月11日(土)　15:00〜

場所：オープンソースラボ

内容：
・進捗状況の報告
　・プログラム（全体の流れなど）
　・参加者（候補者）
　・LT参加者募集
・役割分担
　・レポート
　・受付
　・会場
　・会計
　・写真撮影

その他、個別に打ち合わせをしたいと思います。

**Comment by takaokouji** [comment]
:+1:

**Comment by kenjiSugihara** [comment]
すいません、明日、予定を間違え、県外に出かけてしまいます。
ごめんなさい！！！！
でDoorKeeperで受けつけの仮を作っています。
今のところ管理者権限を倉橋リーダーと私だけにしていますが
その他DoorKeeperの管理者にお加えしたらよい方をお知らせくださーい！
明日のミーティング結果を踏まえて、倉橋リーダーとご相談し、公開準備を進めます。

参加受付
http://matsue-rb.doorkeeper.jp/events/8268  

昼食エントリ
http://matsue-rb.doorkeeper.jp/events/8278

親睦会
http://matsue-rb.doorkeeper.jp/events/8277

**Comment by sho-h** [comment]
1/11 15:00 - 16:15 頃で打ち合わせ+大喜利のデモをしました。出席者など省略しますが、ざっくりとした記録です。
- テーマは?
  - Matsue.rb の文化祭
  - 1 年間やってきた事を発表する
- 参加者
  - 外部からお呼びする方については、DXRuby の作者の方に @hnozaka さんから打診してもらう予定
  - ライブコーディング: あと 2 枠
  - LT は 5 分 x 6 人
  - @yoshiokaCB さんからスタッフに後からお誘いする
- レポート
  - あとひとりふたり欲しい。
  - ただし、今いる人数で残ったパートを分担してもいいと思う
  - 一人は外部からお呼びする方について @hnozaka さんにお願いしようかと思った
  - 他にこちらも @yoshiokaCB さんからスタッフに後からお誘いする
  - 参考(るびま): レポートは ruby の会に送って、同じようにるびまに掲載されます
    - http://magazine.rubyist.net/?0040-MatsueRubyKaigi04Report
    - http://magazine.rubyist.net/?0035-MatsueRubyKaigi03Report
- 受付
  - @kaorimatsuoka さんたち
  - 移動があるので大変だと思うけどよろしくお願いします
- 基調講演
  - @sho-h が年末にメール投げたまま
  - あとで返事を聞いておきます(まだ今年会えていない...)
- 会場
  - 役割として何人か決まってるけど、手が空いている人は手伝ってください
    - @sho-h 注) 現在分担が決まってない人もお願いします
- 公式サイト
  - 嘘を書かないようにだけ気をつけて、趣旨を追記して公開
  - 参考(確認用の仮サイト): http://inoh.github.io/matsuerbkaigi05/
- 募集
  - @ToruKurahashi さんが doorkeeper の権限を持っているので 50 名に設定して公開
  - @sho-h が ruby の会と facebook グループ(Regional Rubykaigi Organizers)への報告
- 中継
  - Ust のアドレスを決める必要がある
  - ユーザを誰にするか決める必要がある
    - 従来通り or not
    - ユーザに紐づいてしまう点を考慮して決める
  - 他に公開までは広告が流せるのでその素材が欲しい
  - 中継できるのは OSS ラボのみになるだろう
    - LT や大喜利は録画だけしておいて後で挙げるなど
    - 上(テルサ)でやるのは？
    - 準備に時間がかかるので、ちょっと難しい
    - なので録画くらい
- 当日
  - サブスクリーンで twitter を流す予定
  - なにかあれば @takaokouji さんが話を拾ってくれる予定
- T シャツ
  - お披露目
  - 加工に 3 日 〜 1 週間程度必要
  - 2/8 の定例会で決を取ります
  - 全面を @takaokouji さんと @KatoAtsue さんでもう少し相談して fix
- 大喜利
  - スクリーンに 4 分割して表示した画面に各個人の PC から接続、コード編集すると反映
  - これでお題(デモでは 1..50 の和？)を解くことでワイワイやる
  - Ruby Jr. の時間が 2 時間ある
  - Ruby Jr. の観客とどっちにするかは自由
  - デモに関する意見募集中

**Comment by sho-h** [comment]
把握してる宿題についての現状です。

> - 参加者
>   - 外部からお呼びする方については、DXRuby の作者の方に @hnozaka さんから打診してもらう予定

@hnozaka さんから 1/14 朝に打診していただいて返事待ちです。

> - 基調講演
>   - @sho-h が年末にメール投げたまま
>   - あとで返事を聞いておきます(まだ今年会えていない...)

まつもとさん OK でした。「まる 1 日はいれないけど大丈夫」との事です。

> - 募集
>   - @sho-h が ruby の会と facebook グループ(Regional Rubykaigi Organizers)への報告

前者への報告が完了してて、後日後者にも報告します。

(ところで宿題が全部終わったら close するというよりはそれぞれ Issue 発行して個別がいいですかね？)

**Comment by yoshiokaCB** [comment]
@sho-h さん
個別にした方が良いと思ったので、分けてみました。既にあるissueに移せるところは移してみました。

**Comment by Takashi-U** [comment]
ライブコーディングの内容や出演者について
https://github.com/matsuerb/matrk05/issues/12
