### ISSUE TITLE
開催目的を明確にする

### ISSUE THREAD

**Issue by inoh** [matsuerb/matrk05#14]

**Comment by Takashi-U** [comment]
@inoh @yoshiokaCB 

http://matsue.rubyist.net/matrk05/

Webでは「目的」が掲載されていますが、こちらはcloseで良かったでしょうか？
それとも、何らか追記しておくべき事があったでしょうか？

今更でごめんなさい…

**Comment by inoh** [comment]
すみません。
自分で開いておきながら放置していました。
ホームページに載せる目的を明確にしたかったのでクローズでいいと思います。
クローズしておきます！
