### ISSUE TITLE
Ustreamの関係

### ISSUE THREAD

**Issue by amidaku** [matsuerb/matrk05#15]
Ustreamのチャンネルを作成しました。
http://www.ustream.tv/channel/matsuerubykaigi05

中継日までの告知としてスライドショーを流す事ができます。
流す写真や画像等の素材をください。

**Comment by amidaku** [comment]
告知素材無いっすか？　.......と投げてみるテスト。

**Comment by yoshiokaCB** [comment]
あっ、すみません。準備します。

**Comment by amidaku** [comment]
Ustream関係でレイアウトと機材の接続系統をwikiに追加しました。
関係の方ご確認いただけませんでしょうか。
問題ございましたら、ご指摘ください。
https://github.com/matsuerb/matrk05/wiki/Equip-ustream

**Comment by yoshiokaCB** [comment]
確認しました。私は問題ないと思います！

**Comment by Takashi-U** [comment]
@amidaku @yoshiokaCB こちらcloseで良さそうに見えますがいかがでしょう？

**Comment by amidaku** [comment]
素材をまだまだ沢山待ってましたが時間切れですね。
閉めてください。
