### ISSUE TITLE
Doorkeeperの内容確認

### ISSUE THREAD

**Issue by ToruKurahashi** [matsuerb/matrk05#16]
Doorkeeperの内容を確認して下さいね。
![matsuerubykaigi05a](https://f.cloud.github.com/assets/1610316/1893501/d73f62a6-7a99-11e3-8258-c85727a47465.png)
![matsuerubykaigi05b](https://f.cloud.github.com/assets/1610316/1893502/d7424d54-7a99-11e3-94ad-dfe76200595a.png)
![matsuerubykaigi05c](https://f.cloud.github.com/assets/1610316/1893503/d747205e-7a99-11e3-91c6-e3abc943bd1a.png)

**Comment by kenjiSugihara** [comment]
倉橋先輩、お疲れ様です！
昨日はごめんなさい。そして早速の更新を有難うございます！
イベント本体、LT大会は問題ないと思います。
親睦会は、内容も変わってませんが、まだ場所、時間などが
決定してないと考えればいいでしょうか？
もし、やぁにするのであれば、時間、人数（現時点ではMAX50？）など
だいたいのところで予約もしますので、遠慮なくご指示ください！！

**Comment by ToruKurahashi** [comment]
杉原大先輩、お世話になります。
現在のステータスは、ここに添付しているDoorkeeper画像の内容を「吉岡さん」に確認して頂いて、OKが出れば公開するという状態です。
杉原さん、この後の対応よろしくお願いします。

**Comment by Takashi-U** [comment]
後輩達、Good job!!!

**Comment by yoshiokaCB** [comment]
確認遅くなってすみません。

■MATSUE RUBY KAIGI 05について
昼食とRuby会議は明確に申し込みを分けておいた方が良いかと思ったので、Ruby会議の時間から昼食の時間を削除したいです。

■MATSUE RUBY KAIGI 05 昼食（LT大会）について
イベント詳細をMATSUE RUBY KAIGI 05と同じように整えてみました。

■MATSUE RUBY KAIGI 05 懇親会について
懇親会は20時から「やぁ」でMAX50でいきましょう！

## MATSUE RUBY KAIGI 05

2014/3/15(土) 13:25〜17:30

イベント詳細
■開催日：2014年3月15日(土)
■時　間：13:25〜17:30

## MATSUE RUBY KAIGI 05 昼食（LT大会）

2014/3/15(土) 11:30〜13:00

イベント詳細

3/15(土)の13:25-1730、松江テルサ別館2F「松江OSSラボ」で開催する松江Ruby会議05のランチタイムに開催するLT大会です。
おいしい旬の食材を楽しみながら、Rubyへの思いをTalkしましょう！

以下追加
■開催日：2014年3月15日(土)
■時　間：11:30〜13:00
■主　催：Matsue.rb(まつえるびー)
■その他：
　・松江Ruby会議05のお申し込み　会費：無料
　　（url）
　・親睦会のお申し込み　会費：4,500円
　　（url）
■お問い合わせ
　松江Ruby会議05に関するお問い合わせ…（省略）

## MATSUE RUBY KAIGI 05 懇親会

2014/3/15(土) 20:00〜22:00

イベント詳細
■開催日：2014年3月15日(土)
■時　間：20:00〜22:00
■主　催：Matsue.rb(まつえるびー)
■その他：
　・松江Ruby会議05のお申し込み　会費：無料
　　（url）
　・昼食（LT大会）のお申し込み　会費：1,000円
　　（url）
■お問い合わせ
　松江Ruby会議05に関するお問い合わせ…（省略）

## 

上記、確認してもらって特に問題が無ければこれで公開をしちゃってください。
ちなみに質問ですが、公開後も修正か可能でしょうか？
ホームページが公開されたらホームページのアドレスをどこかに追加したいです！

以上、よろしくお願いします。

**Comment by kenjiSugihara** [comment]
まずは取り急ぎ、倉橋キャップ、有難うございました！
受付サイト、並びに性恥、いえ聖地「やぁ」の予約はお任せください！！

**Comment by yoshiokaCB** [comment]
あっ、午後の部の「MATSUE RUBY KAIGI 05」のイベント詳細は変更箇所しか書いてないので、ベースは @ToruKurahashi さんが書かれたものを使用してください。
よろしくお願いいたします。

**Comment by kenjiSugihara** [comment]
@yoshiokaCBさん、土曜日はすいませんでしたぁー！
またサイトの確認を有難うございます。
本チャンのイベント詳細もかしこまりです！

懇親会については、
・名称は井上さんと調整しまして、一般的に使用する「懇親会」で統一したいと思いますがいいでしょうか？
・会費は、やぁの一般的な2時間呑み放題コースの4,000円で調整したいと思います。

やぁの予約もしまして、今夜中に受付サイトはリリースします！
で、リリース後も内容変更は可能ですので、何なりとお申し付けくださ～い。

**Comment by kenjiSugihara** [comment]
おお、倉橋先輩のメッセージで気づきました！
懇親会は参加費4,500円ですね（差額500円を招待者用に補てん）。
失礼いたしました！

**Comment by kenjiSugihara** [comment]
倉橋キャップ、超高級料亭やぁを予約しましたんで、
いまから受付サイトを全て公開します！

うちべっこ先生も受付サイトの管理者に入れさせて頂きました！

**Comment by yoshiokaCB** [comment]
@kenjiSugihara さん
ありがとうございます！
募集ページができるとテンション上がりますね。

適当なところcloseをお願いします。
