### ISSUE TITLE
０次会の会場と内容の決定

### ISSUE THREAD

**Issue by ToruKurahashi** [matsuerb/matrk05#17]
０次会についてですが、皆様にご指導を頂きながら、なんとか「ライブコーディング大喜利」をメインイベントとして進めさせて頂こうかと考えています。
会場については、テルサの「研修室２」を１７時から仮予約しました。２４席あります。
研修室での飲食は可とのことですので、飲み物（アルコール、ソフトドリンク）、軽食（スナック等）を購入して持ち込みます。
飲食代の費用は、参加者で割り勘にしようかと考えています。ご意見をお聞かせ下さい。
よろしくお願い致します。

**Comment by Takashi-U** [comment]
場所だけ確保の方が、後々いろいろとアイデアが出たときや、状況に応じて極端な話当日でも柔軟に対応出来そうな印象を受けます。

Ruby.Jrの裏番組としては、良い方針だと僕は感じました。囲碁的には軽い手を打っているような感覚です。

**Comment by ToruKurahashi** [comment]
テルサ「研修室２」の仮予約期限が本日までです。本予約にしてもよろしいでしょうか（本予約にするとキャンセルした場合に料金が発生します）。

**Comment by yoshiokaCB** [comment]
本予約してもらって、OKです！

**Comment by ToruKurahashi** [comment]
申込書の「催事名称（催事案内板への表示内容、２０文字以内）」の欄には
「18:00〜19:30　松江Ruby会議05（第2会場）」
と記載したいと思いますがどうでしょうか。
音響ワゴンやマイクなどの備品はどうしましょうか（岩石さん？）。

**Comment by ToruKurahashi** [comment]
本予約しました。一応、音響ワゴン一式（マイク１本含む）＋マイク２本を利用設備として登録しています。
また、松江Ruby会議05のWebサイトを見ると「テルサ会議場（仮）」となっていますので、「テルサ研修室２」に変更して頂けると助かります。

**Comment by yoshiokaCB** [comment]
ありがとうございます！

**Comment by kenjiSugihara** [comment]
くらっと先輩！昨日吉岡さんとお話しまして、費用の件、了解を頂きました！
僕の上長も口頭でOKもらってます。
これは特にDoorKeeperは作んなくてもOKですかね？
（皆な流れで参加するか決めそうな）

**Comment by kenjiSugihara** [comment]
って言いながら席数が決まってるんで、受付サイトはあった方がいいのかな？
ご意見をヨロピコ！

**Comment by ToruKurahashi** [comment]
杉原大先輩、ありがとうございます（すっかり忘れてました汗）。もう、杉原さんなしでは生きていけません。
受付サイトの件ですが、研修室２へパイプ椅子を頼むことも出来ますし、とりあえず受付サイトはなしで無制限に受け入れたいと思います。

**Comment by Takashi-U** [comment]
@kenjiSugihara @ToruKurahashi 
場所が確保できているということであれば問題無いと思います。closeしておきますが、問題があれば再開してください。
