### ISSUE TITLE
全体ミーティングのお知らせ　（2/8）

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk05#18]
ご連絡が遅くなりましたが、今週末に全体ミーティングを行います。
ご都合が付く方は、ご参加をお願いいたします。

---

■時間
・2月8日　14時〜　（一時間程度予定）

■場所
・オープンソースラボ

■ミーティング内容
・ライブコーディングリハーサル
　・リハーサル後皆さんのご意見をお聞きしたいです。

・進捗状況の報告
　・LT参加者 
　・ゲスト講演者の報告 
　・ライブコーディング出演者報告

・役割事の確認
　・レポート
　・会場
　・UST
　・受付
　・会計
　・懇親会
　・Tシャツ
　・写真係
　・Web

・当日の準備など確認

**Comment by yoshiokaCB** [comment]
ちなみにライブコーディングのリハーサルの目的は以下のようなことを考えています。

## 
1.  司会・解説者の練習　一度経験しとくと当日のリハーサルもスムーズにできるはず。
2.  出演が決まっている人へ司会・解説者との連携の参考にしてもらう。
3.  スタッフと会のイメージを共有する。また、もっとこうしたら等のご意見がほしい

**Comment by sho-h** [comment]
2/8 14:15 - 14:未明 頃で打ち合わせ+ライブコーディングのリハーサルをしました。出席者など省略しますが、ざっくりとした記録です。今回は忘れてて後から思い出して記録にしたので捏造がありえますのでご注意ください。
- @yoshiokaCB さんから現状報告
  - プログラムについて
    - [ライブコーディング全員決定](https://github.com/matsuerb/matrk05/wiki/Program#wiki-%E5%8D%88%E5%BE%8C%E3%81%AE%E9%83%A8)
    - [LT はあと一人](https://github.com/matsuerb/matrk05/wiki/Program#wiki-lt%E5%A4%A7%E4%BC%9A%E7%99%BA%E8%A1%A8%E8%80%85)
  - ライブコーディングについて
    - twitter を流しながらやろうと思う
  - T シャツについての希望者の確認
    - 2/8 では出席のホワイトボードに記載
    - 2/8 に来れなかった方については 2 月中で希望を
- ライブコーディングのリハーサル
  - @yoshiokaCB さんから 15 分版を
  - twitter で賑わしながら+賑わし
  - @takaokouji さんがやる際は @sho-h も賑わし(聞いてましたけどわすれていました)
- その他個別に @yoshiokaCB さんから相談する

個別のお話は個別のチケットで。

**Comment by yoshiokaCB** [comment]
@sho-h さん
ありがとうございます。
