### ISSUE TITLE
当日の集合時間について

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk05#19]
さて、松江Ruby会議05がいよいよ来週と迫ってまいりました。
それで当日の集合時間ですが、9:30にオープンソースラボ集合でお願いします。
（ご都合のつかない方は多少遅れても大丈夫ですよ。）
当日は簡単なミーティングをして、会場準備をしたり、Tシャツを買われた方に配ったりします。
時間はあまると思いますので、余った時間はみんなでわいわい出来たらいいなと思っています。

それではよろしくお願いいたします。

**Comment by Takashi-U** [comment]
@kenjiSugihara さんはまだですがcloseします。
