### ISSUE TITLE
昼食（LT大会）の会場選定

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk05#2]
「パーティスタイルスペース　ファン」と「エキマエシキアン」の利用時間が17:00〜ということで、昼食に利用できないので、大人数が入れてLTが出来る会場を探しています。
今のところ候補として、テルサ４階会議室で弁当を食べながらLT大会をするか、スサノオカフェが候補として上がっています。
@Takashi-U さん、 @amidaku さん、 @ToruKurahashi さん @kenjiSugihara さん また相談させてください。

**Comment by Takashi-U** [comment]
@kenjiSugihara さんにもリプっておきまーす！

**Comment by kenjiSugihara** [comment]
あざっす！
今日の昼に県セミナー講師の堤さん（VC）、福田さん、鶴原さんと「旬門」でランチしました。
地のモノを使った週替わりランチが1,000円。しかも有り得ないボリュームでした（堤さんもビックリ）。
ただ、観光客、集団客で満席。もし、ランチ（LT）で使う場合は早目に予約しておいた方が良さそうです。
※集団で来ていたおばちゃんたちが旬門でLTやってました（なんだったんだろう）。
一応、会場候補としての報告でした。

**Comment by Takashi-U** [comment]
Facebookでの会話であった庵タンドールですが、サイトを拝見するとランチ営業はやっているようです。
設備はあるようですが、その時間でLTが出来るかは謎ですね。一応挙げておきます。

http://www.untendre.com/

**Comment by yoshiokaCB** [comment]
失礼しました。
杉原さんが抜けておりました。

**Comment by kenjiSugihara** [comment]
いえいえ！

**Comment by sho-h** [comment]
旬門というとそういえば、Ruby 温泉ハッカソン2012 の昼食が旬門でしたね。団体用の大広間が広いので LT するのに向いてそうです。本当にボリュームがすごいです(膳が大きいですw)。ここにする場合はPC 広げる人を考慮した余裕のある席の配分がいいと思いました。

**Comment by ToruKurahashi** [comment]
吉岡さんと相談して第一候補は「旬門」にしました。私の方から旬門へ問合せをしてみます。

**Comment by yoshiokaCB** [comment]
ありがとうございます！
引き続きよろしくお願いします！！

**Comment by amidaku** [comment]
スレ的にココが妥当かどうか微妙ですが、質問します。
LTも中継しますか？

**Comment by yoshiokaCB** [comment]
あっ、考えてなかったです。でも環境的に配信は厳しいのでは？

**Comment by amidaku** [comment]
中継配信するとなると回線的に低画質なものにならざるを得ないですね。
たとえば１カメラで録画して、後日録画をＵＰするという事も考えられますがいかがでしょうか。
それであれば、普通の画質の物が流せます（中継では無いですが）。

**Comment by yoshiokaCB** [comment]
了解です。
とりあえず、中継配信は技術的に難しそうなので、無しにしたいです。
せっかくなんで、録画ができると良いかもしれません。

**Comment by amidaku** [comment]
では、中継は無しで、可能なら録画をするという方向で進めます。

**Comment by ToruKurahashi** [comment]
皆様、遅くなってすみません。

「旬門」に連絡を取り、場所の予約をしました。内容は以下です。
時間：開場11:00〜、料理11:30〜
人数：20〜30名程度といいました（確定次第連絡）
部屋：大広間（大きい机５つ？）
料理：別途連絡（今のところ1000円/人の個別料理を考えています。）
LT関連：スクリーン、プロジェクタの持ち込み可
そのた：他のお客の迷惑にならないようにとの事なので、マイクは無しの方がよいかも。

以上ですが、他に確認することがあれば聞きます。

**Comment by yoshiokaCB** [comment]
@ToruKurahashi さん
ご予約ありがとうございます。
ちょっと確認というかご相談ですが、現在スタッフだけで20名くらいいますので、一般参加者を考えるともう少し人数が入ると良いかなと思います。どれくらい対応できるか教えてもらえると助かります。
あっ、30名が限界ならそれはそれで募集をすれば良いです。

**Comment by ToruKurahashi** [comment]
旬門は60名まで大丈夫だそうです。ということは、同じ部屋（大広間）に他のお客も入るということですね。

**Comment by yoshiokaCB** [comment]
了解です！問題なさそうでよかったです。
他のお客さんが入るのは仕方ないですね。

**Comment by kenjiSugihara** [comment]
ちなみに申込サイトの定員はいくらにしましょうか？

**Comment by Takashi-U** [comment]
昼食も懇親会同様に募集っすかね？
人数も気になりましたが、そこも気になってます。

**Comment by yoshiokaCB** [comment]
昼食も懇親会同様に定員決めてDoorkeeperで募集にしようと思っています！

**Comment by Takashi-U** [comment]
募集ページもご準備いただきましたのでcloseします。
