### ISSUE TITLE
レポート対応

### ISSUE THREAD

**Issue by sho-h** [matsuerb/matrk05#20]
今日はお疲れさまでした&ありがとうございました。松江Ruby会議05のレポートを作成で本 Issue を発行します。作成したレポートは Rubyist Magazine に掲載されます。

参考に過去のレポートは以下です。
- http://magazine.rubyist.net/?0040-MatsueRubyKaigi04Report
- http://magazine.rubyist.net/?0035-MatsueRubyKaigi03Report
- http://magazine.rubyist.net/?0034-MatsueRubyKaigi02Report

GH でやるとるびまでの公開前に見えちゃうので Issue だけ作ってメールベースか何かでやるのがよさそうかなと考えています。問題ないようであれば、以下の方々と FB や DM とかでアドレスを交換させてください(Wiki に登場する順)。FB のプライベートグループなどでもいいかなと思います。
- @shakkun さん
- @Takashi-U さん
- @hnozaka さん
- @yoshiokaCB さん
- @sho-h
- @nobuyuki さん
- @ToruKurahashi さん

来場者数(doorkeeper の昼食→本番では参加者の方は追加のみだったので飛び込みがなければ36名)、ust 視聴人数(3/16 00:30 現在 124名？)は差分の確認後ここに掲載して後から確認できるようにしようかと思います。

**Comment by yoshiokaCB** [comment]
@sho-h さん
先日はお疲れ様でした。
色々ととりまとめいただきありがとうございました。

来場者の件ですが、自分の把握している限り、昼食はDoorkeeperの人数にはmirichiさんが含まれていませんので、プラス１です。
また本番では、まつもとさんとmirichiさんが含まれていないのと当日フラッと来られた方もおられたはずなので、正確な数字を受付の方（杉原さん、松岡さん、ゆんさん）が把握してないか確認してみますね。

**Comment by sho-h** [comment]
おぉ、そのとおりですね。> まつもとさんと mirichi さん
では正確な数字はお願いしますー。

あと、あみだくさんが [togetter](http://togetter.com/li/642795) をまとめてくださったので、このURLもレポートに張ろうかと思います。ありがとうございました。実は期待ageしながら黙ってました(←最低

**Comment by shakkun** [comment]
徳永翔二さんがdoorkeeperの参加登録されていませんでしたので追加ですね。

**Comment by sho-h** [comment]
了解ですー。では、午前の部が33名(31+2名)で、午後の部が39名(36名+3名)としますね。

**Comment by Takashi-U** [comment]
https://github.com/matsuerb/matrk05/issues/20#issue-29495040

レポートの連絡手段ですが、メールでのやり取りということで @sho-h さんからコメントいただいております。

メールアドレスの相互交換につきましては、私がとりまとめて、その後皆さんに各人のアドレスへ一斉送信してアドレスを確認したいと思っています。

 というわけで、twitterやfacebookでメールアドレスを送っていただいてもOKですし、私のアカがわからないという方は、私のサイトに「お問い合わせ」ページを作っていますので、そちらからお知らせください。
http://uchibe.net/

よろしくお願いします！

**Comment by yoshiokaCB** [comment]
あっ、午後の参加人数は40人（63名+4名）でお願いします。

**Comment by sho-h** [comment]
あら、もしやまつもとさん、mirichiさん、徳永さん、ふらっとさんで+4名でしたか。了解ですー。

**Comment by sho-h** [comment]
ところで、集めたメールアドレスは matsuerubykaigi05 _at_ googlegroups.com に登録してやりとりしてもいいかなと思ってたりするのですが、誰がメンバーとか使ったらだめとかわかりますか？ (@yoshiokaCB さんか @inoh さんが把握？)

問い合わせが来るかもしれないので、結局使わないかもですが。

**Comment by inoh** [comment]
googlegroupsは作成したもののまだ投稿はないのでレポート班のやりとりとして使用してもよいように思いました。
とりあえず私と @yoshiokaCB さんをアサインしているので必要ならまたメンバ追加します。

**Comment by yoshiokaCB** [comment]
私もレポート班で使用して問題ないと思います。

**Comment by sho-h** [comment]
おぉ、ありがとうございます。じゃあ使う事にして、matrk05 の問い合わせのページからはアドレス消しておこうかななどと思ったりです。

**Comment by Takashi-U** [comment]
MLの権限を付与していただけると助かります。現在把握している皆さんを登録しますので…。

**Comment by inoh** [comment]
@sho-h 
ページからアドレスを消してプルリクしておきます！
@Takashi-U 
登録していただけると助かります！
MLに登録するためにメールアドレスが必要になりますので @Takashi-U さんのメールアドレスを教えてもらえるとうれしいです。
他に登録してほしい人のメールアドレスを教えてもらえれば私の方でも登録します！

**Comment by sho-h** [comment]
@inoh ありがとうございますー。反映までしました。

**Comment by inoh** [comment]
@sho-h ありがとうございます！

**Comment by sho-h** [comment]
[RegionalRubyKaigi:1190] Re: 松江Ruby会議05(3/15)のお知らせ で送付doneです。

**Comment by sho-h** [comment]
47 号に掲載されてないと思ったら、皆さんこっちに Issue 立ててらっしゃる...まだよくわかってないけど、reopenします。
- https://github.com/rubima/rubima/issues

**Comment by sho-h** [comment]
やっと終わらせる事ができた。
