### ISSUE TITLE
大喜利リベンジ

### ISSUE THREAD

**Issue by sho-h** [matsuerb/matrk05#21]
リベンジマッチする場合のためにとりあえず 1 つ目を発行してみます。

とりあえず、以下のように感じました。
- 何人か巻き込んでいくつかの Issue を発行するのがいいように思った(matrk06 にすべき？)
  - 問題を考える人、当日事前に環境を整える係の人、システム面の選定などを進める人
- 当日事前に環境を整える点について
  - 1 時間前には準備が終わる予定希望 → 特定の係の人が必要なんじゃね？と思った
- システム面の選定などを進める人
  - 1 月にはわかってた問題がそのままなのが辛かった
    - 編集時に日本語は表示できるが実行時に日本語が表示できない
    - うまく編集できないケースがある
    - その他に新しく見つかった問題として、タイプすると過去の内容がカーソル位置に全ペーストされる場合がある
  - [codiad](http://codiad.com/) を継続して使うかをまずみんなで相談した方がいい？
    - 現状のまま進めるパターン
      - 問題点を解決するようコード修正するなり、運用回避するなり
      - 事前に問題なく操作できる環境の組み合わせ一覧があるとなおよい
    - 別のツールで代替するパターン
    - そもそもクラウドIDEツールを使わずにウィンドウを 4 つ表示して更新して表示し続けるパターン

次回、Matsue.rb定例会で話したりします？

**Comment by amidaku** [comment]
大喜利システムに興味があります。
要る事と、要らない事を整理して、作ってみたいなあと思ってます。
現時点で、システム化の目処を立ててるわけでは無いですけど。

**Comment by sho-h** [comment]
(_´∀｀_) やだ、かっこいい.... (自分のキャラを見失っている

**Comment by amidaku** [comment]
まあ、出来上がるかどうかも全くわからないですが、あのnice tryを無駄にしたく無いので。

**Comment by yoshiokaCB** [comment]
次回もぜひやりましょう！
自分は単純にスクリーンとプロジェクタを3-4つ集めようと考えてましたw
でも今回のシステムは各自のPCで確認できるので、それは便利ですよね。極端な話、遠隔地でもできるし。

**Comment by Takashi-U** [comment]
僕の骨を拾って下さってありがとうございます。。

**Comment by amidaku** [comment]
仕込みが必要で、つぎはぎだらけですが、なんとか大喜利システムできそうです。パッケージ化できない（今回のように１アプリケーションでの対応では無いです）ので、どこでもいつでもというわけにはいかないですが、イベント毎の対応で何とかなりそうです。いつかの.rbで検証してみましょうね。

**Comment by sho-h** [comment]
今日はリベンジの日なのでcloseします。

**Comment by Takashi-U** [comment]
リベンジは果たされましたでしょうか？
Reopenなんてことは･･･

**Comment by yoshiokaCB** [comment]
会場で聞いた限りでは評判もよかったので、OKだと思います。
