### ISSUE TITLE
プログラムの確定

### ISSUE THREAD

**Issue by Takashi-U** [matsuerb/matrk05#3]
発表者との折衝やお願いする方の検討等、相手のある事については、この場で議論するのが不適切なものもあるかもしれません。

Issueとして挙げたのは、基本的にはWikiのページを埋めるという意です。

https://github.com/matsuerb/matrk05/wiki/Program

**Comment by Takashi-U** [comment]
レポート班の分担については他のissueとします。（プログラムの確定後の作業のため。）

**Comment by yoshiokaCB** [comment]
今週・来週あたりで大まかなプログラムは決めたいですね。
今のところ、発表者は個別にお願いしようと思ってます。
TLは1月頃から1ヶ月くらい公募してもいいかと思っています。

**Comment by shugo** [comment]
@takaokouji には少し話したのですが、たまには県外から講演者を招待しませんか？
旅費くらいは県内企業に協賛をお願いすれば捻出できるんじゃないかと。
社内調整はしてませんが、うちも出したいと思います。

**Comment by yoshiokaCB** [comment]
@shugo さん
県外からの講演者の件、承知しました。検討したいと思います。
費用に関しては@takaokouji さんから「日本Rubyの会」から支援も期待できるとの話を聞いておりましたので、どのようにしたら良いか相談をしてみます。

また、招待したい人に関してこちらで人脈の無い場合、色々とご相談させていただくかもしれません。
そのときはよろしくお願いいたします。

**Comment by shugo** [comment]
@yoshiokaCB さん
ありがとうございます。よろしくお願いします。

**Comment by sada** [comment]
プログラムを決める際に基調講演についても決めると思うので、こちらに書きます。
以前、基調講演をまつもとさんに頼む話がありましたが、以下のことを決めてから話をした方が良いです。
- 当日の何時から何分までか。(例: 3/15の10:00から30分とか)
- どういう参加者に対して、どういう話をして欲しいか。(例: パーフェクトRubyを読んでいるエンジニア向けとか)

まつもとさんの出張とかの用事と被るといけないので、なるべく早めに決めておいた方が良いです。

**Comment by yoshiokaCB** [comment]
@sada さん
早め！了解です！！
来週には具体的にご依頼できる予定です。
ありがとうございます。

**Comment by sada** [comment]
@yoshiokaCB さん
ライブコーディングの件についても、同じように時間が決まってから参加していただけないか話を持っていこうと思います。
よろしくお願いします。

**Comment by yoshiokaCB** [comment]
@sada さん
了解っす！

**Comment by Takashi-U** [comment]
以下、先輩から後輩への命令により、現在想定しているメモを記載します。

### プログラム

*オープニング  13:30 - 13:35
*基調講演         13:35 - 14:05

*ライブコーディングは一枠30分で３～５つのセッションにする予定です。
- セッション１ 14:10 - 14:40
- セッション２ 14:50 - 15:20
- セッション３ 15:30 - 16:00
- セッション４ 16:10 - 16:40
- セッション５ 16:50 - 17:30
  *クロージング 17:30 -

基本、一枠30分で考えています。

最初の質問5分
ライブコーディング20分
最後の質問5分

　コーダーの希望により、少々枠の長さを変更し、セッションの数も調整したいと思っています。
　要望が無ければ、30分で依頼します。

### 役割

　堅苦しい感じを出したくないので、司会と解説とわけて、複数の人に盛り上げ役をしてもらおうと思っています。
司会（質問者）として、○○さんにライブコーディング全体の盛り上げ役をお願いしようと考えています。
また解説として、技術的なツッコミ役を○○さん他、どなたかにお願いしましょうと思っています。（同時に複数も可）スタッフには積極的にtwitterでつぶやいてもらい、サブスクリーンを設置してそこにツイートを表示したいです。

　司会・解説には可能ならばコーディングの最中に質問ツイートや面白いツイートなどあれば拾い上げて紹介をしてもらったり、コーダーに質問を投げかけたりしてほしいです。（可能なら）

司会：○○さん
解説：○○さん他
コーダー：未定
(コーダー候補)
○○さん
○○さん
（転記者注：氏名は記載しないポリシーで転記しています。）

### 流れ

1.質問（司会・解説とコーダーのやりとり）
2.ライブコーディング（20分程度）
3.質問（twitterから）

#### 1. 質問 ------------------------

　セッションが始まったらいきなりライブコーディングがスタートするのではなく、司会や解説者の方から事前に準備した質問の中から、適当に質問をしてもらい、コーダーの情報を聞き出します。できれば空気を柔らかくしてほしい。

例
・会社は？
　会社での仕事は？
・なぜそのPCを使ってるのか？　（メーカーとOSの選定理由）
　・他のメーカーやOSの感想は？
・エディタは何を使用しているのか
　・どこが気に入っているのか？
　・他のエディタとの比較は？
・開発に使う便利ツールは他にないのか？

　などなど、適当に。場合によっては事前にアンケートのようにコーダーにいくつか質問をしておいて、それを元に司会と解説の方に掘り下げてもらうと良いかもしれません。

　また、出演者が決定したら、Githubなどで事前に聞きたい事をスタッフからも募集もしたいと思っています。ustするんで公募でもいいかも。
　最後に今日はどのようなライブコーディングをしてくれるのか質問をしてから、コーディングをスタートしてもらいます。

#### 2. ライブコーディング ------------------------

　ライブコーディング中は基本的にはコーダーの人に解説をしてもらいながら、コーディングをしてもらおうと思います。
　解説の人にはところどころ、ミスったり、時間が空くときは様子を見て何が起きてるのか解説をしたりしてほしいです。
　また、事前の打合せ（午前中のリハーサル）で、解説側からツッコミたいところや、コーダー側から場をつないでほしいところを言っておいてもらえば、その時に解説者とコーダーのやり取りを入れる形にしたいと思います。
それとコーダーさんの了解は必要ですが、可能なら、ツイートをチェックしてコーダーさんに質問したり、話しかけてみると面白いと思います。出来なければ最期の質問のコーナーにまわします。

#### 3. 質問 ------------------------

　コーディング中にtwitterを使用してハッシュタグ付きでつぶやいてもらう。
　その中の質問や、興味深い意見などをピックアップしてコーダーへ質問などをする。

　自分の方で特に気になる点としては･･･
　色々とライブコーディングの動画をチェックしましたが、もくもくと打つ人もいれば、上手にしゃべりながらする人もいました。（ライブコーディングが一つのパッケージのような人）上手にしゃべりながらのコーディングを期待するのは、コーダーの方にかなり負担だと思うので、黙々と打つ感じを想定しています。それで盛り上がるかどうか。。。

　黙々と打っている場合、説明が少し足りないところや、すごいテクニックを使ったのにさらっと次に進んだり、盛り上がりに欠けそうな気がします。そんな時、解説者の方に目ざとくツッコミを入れてほしいのですが、それがコーダーからするとリズムが狂うし、集中を妨げる可能性もあります。
　なので、解説の方には事前にコードリーディングをしてもらって、打合せのときに「ここのところでツッコミ入れるかもね」など話をしておけば、コーダーの方も、あまり邪魔にはならず、場を盛り上げていけるかもしれません。
（ほとんどアドリブで書く場合はどんなコードを書くか、ある程度把握したいですね。）

　あとは、手が止まったときにちょっと面白いツイートの紹介とかですかね。

　上記踏まえて気になるのが、それぞれコーダーと司会者・解説者の負担がどんなもんでしょうか？
特に解説の方の負担が思ったよりも大きくなるかもしれないのが心配です。
なるべく一人の負担が少ないように、最初の質問などのやり取りは司会者。コーディング中は解説者に振ろうと思った次第です。

　他気になる点やもっとこうしたほうが良いなどありましたらご指摘いただけると助かります。

**Comment by yoshiokaCB** [comment]
@Takashi-U さんありがとうございます！

ライブコーディングの枠の企画です。
しばらく皆さんのご意見がないか様子をみた後、修正の必要なところは修正を加えて、出演者の交渉を行っていきたいと思います。

**Comment by yoshiokaCB** [comment]
まだ、出来るかどうかわかりませんが、「ライブコーディング大喜利」という企画案も出てきています。
まだまだ未確定要所が多いので別のissueを作成しました。

https://github.com/matsuerb/matrk05/issues/11

**Comment by amidaku** [comment]
ちょっと何名か相談あったので、某中学生に出演意思を聞いてみました。
「なにかやってみたい」、「スライドで発表は興味ない」、「ライブコーディングはしてみたい」、「でも時間かかるのでどうかな？」
そんな感じでした。
やらせるならフォローする人が居るんじゃ無いかなという気がしますね。

**Comment by yoshiokaCB** [comment]
私としては、ぜひ参加してくれるとうれしいのですが、誰かフォローしてくれる人はいないですかねぇー。

**Comment by amidaku** [comment]
何かのアルゴリズムで素数判定するプログラムが、うまくいけば30分ぐらいだそうです。時間がネックですよねー。

**Comment by yoshiokaCB** [comment]
うーん。
事前準備なしに、その場で考えて書く予定なんですかね？
ちょっと1月に某氏と相談ですかね？

**Comment by yoshiokaCB** [comment]
@ToruKurahashi さん @kenjiSugihara さん @Takashi-U さん　他関係者の方々（会場準備、受付も関連あり）

昼食のLT大会の枠を11:30 - 13:00 として、午後の部の開始を13:25 - にしてますが問題ないでしょうか？
（LTは5分×6枠程度を想定しています。）
移動・準備等含めて問題点などありましたらご指摘いただけると助かります。

以下、プログラムの予定を更新しています。
https://github.com/matsuerb/matrk05/wiki/Program

**Comment by yoshiokaCB** [comment]
プログラムに関して特にご意見は無いようなので一旦クローズします。
参加者や、細かなことに関しては別のissueを作ります。
