### ISSUE TITLE
懇親会の内容確定

### ISSUE THREAD

**Issue by Takashi-U** [matsuerb/matrk05#4]
20時からの懇親会についてです。
- 会場
- 会費
- 募集（DoorKeeper）

これらを確定させてプログラムのページに転記しましょう。

https://github.com/matsuerb/matrk05/wiki/Program

【留意事項】
Web班への伝達も忘れずに…。
https://github.com/tomo-k/matsuerbkaigi05/issues/5

**Comment by Takashi-U** [comment]
@kenjiSugihara @ToruKurahashi 確定内容に漏れがあれば追記してくださいませ。

**Comment by kenjiSugihara** [comment]
懇親会の会場については、如何しましょうか？

候補の一つ「やぁ」でしたら最大70名まで入れます。
料理＋呑み放題で、2時間4千円で組めます。
※七冠馬はありませんよ。
いずれにせよ観光客が多い中ですので、
決まれば予約を早目にしておいた方が無難です。

DoorKeeper は、本チャン受付、ランチ、0次回とあわせて
準備を進め、URLを早目にフィードバックします。

**Comment by Takashi-U** [comment]
異議ございません。（むしろ望ましいかと。）

**Comment by Takashi-U** [comment]
Web班への伝達はこちら

**Comment by Takashi-U** [comment]
https://github.com/tomo-k/matsuerbkaigi05/issues/5

すみません。間違えてcloseの方を押してしまいました。。

**Comment by kenjiSugihara** [comment]
あ、やぁで決定で良かったですっけ？
よければ、一応、2階を全部仮押さえぐらいの勢いで予約します。

**Comment by takaokouji** [comment]
:+1:

**Comment by ToruKurahashi** [comment]
杉原大先輩、お世話になります。
昨日のミーティングで、懇親会は「やぁ」でいこうということになりました。
５０名で２０時からの予約をして頂けないでしょうか。

あと、吉岡さん「懇親会」なのか「親睦会」なのか統一して頂けると助かります。

よろしくお願い致します。

**Comment by inoh** [comment]
私はホームページ作成で「親睦会」と統一していました。
また正式な言い方があれば直します。

**Comment by ToruKurahashi** [comment]
忘れていましたが、吉岡さんと相談して、「やぁ」での料理は４０００円/人でお願いして、懇親会費は４５００円/人で徴収することにしました。
この差額はRuby会議招待者の懇親会参加費として補填するつもりです。

**Comment by kenjiSugihara** [comment]
倉橋リーダー、参加費の件、ご説明を有難うございました！
先程、超高級料亭「やぁ」の予約Done！

・3月15日（Sat）　20:00～22:00
・50名
#　場所は2階の奥左の部屋を貸切、50名ならここの全員入れます
#　30名ぐらいであれば、貸切ステータスのままだと思います。
・予約名：杉原
・予算：1人4千円
・呑み放題、鍋中心のコース料理

申込み人数の状況を見ながら、私から
1週間前に予約人数の変更を
2日前（申込締切）に一応、確定人数を
お店に連絡しますっす！

みんな大好き伝説の「やぁ」

**Comment by kenjiSugihara** [comment]
懇親会場の予約ができましたので、受付サイト（本体、ランチLT、懇親会）を
公開しますっす！
で、Webチームの井上さんにも報告します。

受付サイトは、公開後もいつでも修正できますので
不備があればご指摘くださいませ！

Have a nice dinner !!!

**Comment by yoshiokaCB** [comment]
＞あと、吉岡さん「懇親会」なのか「親睦会」なのか統一して頂けると助かります。
懇親会でOKです！

@kenjiSugihara さん、 @ToruKurahashi さん　色々とありがとうございます！
これで親睦会の内容は確定ですかね？
OKでしたら適当にcloseお願いします。

**Comment by inoh** [comment]
@kenjiSugihara さん、連絡ありがとうございます！
以前教えていただいたアドレスでホームページを修正しました。

@sho-h さん、@yoshiokaCB さん
松江Rubyのサイトにプルリクエストを送っておいたのでOKなら取り込みおねがいします！

**Comment by yoshiokaCB** [comment]
@inoh さん
ご自分でマージされたんですかね？
ありがとうございます！

**Comment by inoh** [comment]
@yoshiokaCB さん
コミットの差分を確認するつもりが間違えてマージしちゃったっぽいです。
ごめんなさい X)
内容だけ確認してもらってOKなら公開と拡散ですかね

**Comment by Takashi-U** [comment]
Wikiへの転記完了しました。
Web班に作業もしていただいていますね。

https://github.com/matsuerb/matsuerb-nanoc/pull/116

**Comment by Takashi-U** [comment]
https://github.com/matsuerb/matrk05/issues/6

サイトへの反映はこちらのissueで挙げられてるのでcloseします。
