### ISSUE TITLE
Matsue.rbのTシャツ作成

### ISSUE THREAD

**Issue by Takashi-U** [matsuerb/matrk05#5]
Tシャツについては間に合えばというお話でしたので、ToDoとせずにメモとして残しておきます。

**Comment by Takashi-U** [comment]
@KatoAtsue @takaokouji 具体的になってきましたら作業分担しますので、Issueに挙げてくださいませ！

**Comment by KatoAtsue** [comment]
$B>5CN$7$^$7$?!#$I$&$b$"$j$,$H$&$4$6$$$^$9!#(B

2013/12/9 Takashi Uchibe notifications@github.com

> @KatoAtsue https://github.com/KatoAtsue @takaokoujihttps://github.com/takaokouji$B6qBNE_$K$J$C$F$-$^$7$?$i:n6HJ,C4$7$^$9$N$G!"(BIssue$B$K5s$2$F$/$@$5$$$^$;!_(B
> 
> $B!=(B
> Reply to this email directly or view it on GitHubhttps://github.com/matsuerb/matrk05/issues/5#issuecomment-30106115
> .

## 

$B2CF#8|7C(B
atue.kato@gmail.com

**Comment by amidaku** [comment]
文字化けしちゃったみたいですね。 > 加藤さん
メールソフトの文字コード指定が変わっちゃってるかも。

「$B>5CN$7$^$7$?!#$I$&$b$"$j$,$H$&$4$6$$$^$9!#(B」
　↓
「承知しました。どうもありがとうございます。」

**Comment by KatoAtsue** [comment]
岩石さんどうもありがとうございます。
設定を変えてみましたが、なおってなかったらまた教えていただけるとありがたいです。

2013年12月10日 20:02 Mutsumi IWAISHI notifications@github.com:

> 文字化けしちゃったみたいですね。 > 加藤さん
> メールソフトの文字コード指定が変わっちゃってるかも。
> 
> 「$B>5CN$7$^$7$?!#$I$&$b$"$j$,$H$&$4$6$$$^$9!#(B」
> ↓
> 「承知しました。どうもありがとうございます。」
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/matsuerb/matrk05/issues/5#issuecomment-30216515
> .

## 

加藤厚恵
atue.kato@gmail.com

**Comment by amidaku** [comment]
加藤さん、大丈夫ですよ！

**Comment by KatoAtsue** [comment]
岩石さん、どうもありがとうございました。

**Comment by takaokouji** [comment]
まことに勝手ながら担当を加藤さんに変更させてもらいました。
もちろん私も担当者として作業しますが、ほとんど加藤さんに作業していただいているという :sweat_smile:

**Comment by takaokouji** [comment]
あと、Tシャツのデザインを少し考え直してみて、前面に印刷してもいいかなと思いました。
加藤さんの好意で胸ポケット部分の印刷はやっていただけるとのことだったのですけどね～
実物を確認してから、加藤さんと相談して決めたいと考えています！

**Comment by Takashi-U** [comment]
:+1:

**Comment by yoshiokaCB** [comment]
1/11 ミーティングメモ
- T シャツ
  - お披露目
  - 加工に 3 日 〜 1 週間程度必要
  - 2/8 の定例会で決を取ります
  - 全面を @takaokouji さんと @KatoAtsue さんでもう少し相談して fix

**Comment by Takashi-U** [comment]
facebook上で注文宣言をいただいていますのでcloseしておきます。
