### ISSUE TITLE
Webページの作成

### ISSUE THREAD

**Issue by Takashi-U** [matsuerb/matrk05#6]
松江Ruby会議05の特設ページを作成します。
具体的な作業については下記でWeb班が行っています。

https://github.com/tomo-k/matsuerbkaigi05

ですので、Web作成についての具体的な作業については当該repositoryにて行い、公式サイトへのコミットの段になったらこちらのIssueとしましょう。

**Comment by Takashi-U** [comment]
@tomo-k @ReikiNagashima @inoh 何か抜けがあったら補足してください。よろしくお願いします。役割ページに代表者が無い事と、tomo-kさんのところの作業ということで、tomo-kさんにassignしています。

**Comment by inoh** [comment]
代表者決めないといけないですね。
チーム内で少し話をしてまた埋めておきます。

**Comment by inoh** [comment]
最新のページについてレビュー用としてgh-pagesに作成しました。
内容とかまだ整理できてないので間違いとか追加したい内容とかあれば意見いただけるとありがたいです。

http://inoh.github.io/matsuerbkaigi05/

ある程度情報がまとまってきたら正式な公開時期は相談したいです。

**Comment by yoshiokaCB** [comment]
おお！めっちゃいいですね！！
参加申し込みなどは準備中でも構わないと思いますがどうでしょうか？
出来れば年内に公開したいですね。
あっ、ただ、地方Ruby会議への連絡が先なので、それからですね。

**Comment by inoh** [comment]
内容はほぼ未確定情報なのである意味全部準備中かもしれないですね。
参加申し込みは準備中にしておきます。
エントリとか広報もあると思うので公開は確かに年内とか早めがいいかもですね！

**Comment by inoh** [comment]
とりあえずログをおってわかる範囲でホームページ（ http://inoh.github.io/matsuerbkaigi05/ ）の手直しをしました。
今度の打ち合わせのときに公開するための最低条件をまた確認させてください。
ホームページに関するissueは https://github.com/tomo-k/matsuerbkaigi05/issues で管理していますが、私が今把握している修正必要箇所は下記です。
- Doorkeeperのアドレス  
  - 参加受付
  - 親睦会
  - 昼食エントリ（必要なら）
- 午後の部の中継先（USTREAMのチャンネルアドレス）
- メールアドレス
- プログラム

もし決まっていることあればまた教えてください。

**Comment by yoshiokaCB** [comment]
@inoh さん
諸々作業ありがとうございます。
今週末打ち合わせがあるのでそのときに細かなことは確認しましょう。

**Comment by kenjiSugihara** [comment]
@inoh さん、今日、明日のところで参加受付、懇親会、昼食エントリのサイトURLをお知らせしまーす！

**Comment by amidaku** [comment]
ustなどのurlですが、明日決める...というかチャンネルを作ります。
ちゃんねるを作るにあたって、宣伝用に画像など欲しいのですが、明日のミーティングの際にお話ししますね。

**Comment by kenjiSugihara** [comment]
DoorKeeper担当です。
もちろん公開は未だですが、URLは以下になります。

参加受付
http://matsue-rb.doorkeeper.jp/events/8268  

昼食エントリ
http://matsue-rb.doorkeeper.jp/events/8278

親睦会
http://matsue-rb.doorkeeper.jp/events/8277

明日の打ち合わせで倉橋リーダーとご相談し、受付サイトの公開準備を進めたいと思います。
で、すいません、明日は欠席させてください･･･

**Comment by inoh** [comment]
@kenjiSugihara さん
アドレスの登録ありがとうございます！
とりあえずホームページへアドレスは反映しておきます。
また公開時期は明日相談させてください。
@amidaku さん
了解しました！
ustについても明日相談ということで！

**Comment by amidaku** [comment]
ustreamチャンネル取りました。
url: http://www.ustream.tv/channel/matsuerubykaigi05
です。

**Comment by kenjiSugihara** [comment]
@inoh さん、お疲れ様です！土曜日はすいませんでしたぁー！

受付サイト（Kaigi、ランチLT、懇親会）は吉岡さんにご確認頂きましたので
懇親会場「やぁ」の予約を今日抑え次第、今夜サイトを公開する予定です。

また、夜のDrinkPartyですが、一般的な名称の「懇親会」で統一しようかと思いますが
よろしいでしょうか？

**Comment by inoh** [comment]
@kenjiSugihara  さん、お疲れ様です！
「懇親会」了解しました。直しておきます！

**Comment by kenjiSugihara** [comment]
@inoh さん、おつかれさまでーす！

懇親会場の予約Doneしましたので
受付サイト（本体、ランチLT、懇親会）をさきほど公開しました！

吉岡さんのご指示で本体サイトの公開後に、
受付サイトにそのURLを貼り付けますので
またタイミングを教えてやってくださいませ！

**Comment by yoshiokaCB** [comment]
@sho-h さん @takaokouji さん
とりあえず、matsuerb-nanoc へマージされてますので、サイトへの反映をお願いします。
あと、地方Ruby会議へプロキシの設定も依頼していただけると助かります。
よろしくお願いします。

**Comment by sho-h** [comment]
プロキシ設定了解です！
サイトへの反映は matsuerb.github.io に generate した html を push したらいいんでした？ > @takaokouji

**Comment by sho-h** [comment]
あ、サイトを公開しましたの行、1/12 のままにします？(まぁいいかという気がしてもいるのですが一応

**Comment by yoshiokaCB** [comment]
@sho-h さん
まったく問題ないですよ！
ありがとうございます！！

**Comment by sho-h** [comment]
おぉ、さきほど1/17にしてしまったのでした。公式サイトで見れるようにしました。これからプロキシの設定を依頼します。

前も確認したかもですが、以前が以下なので、
- http://regional.rubykaigi.org/matsue03
- http://regional.rubykaigi.org/matsue04

今回は以下にします？それとも公式サイトと同じで matrk05 がいいんでしたっけ？
- http://regional.rubykaigi.org/matsue05

**Comment by yoshiokaCB** [comment]
これまでの流れがあるので、「 http://regional.rubykaigi.org/matsue05 」でいいと思います。

**Comment by sho-h** [comment]
依頼doneです。設定いただいたらcloseします。

**Comment by inoh** [comment]
サイト公開ありがとうございます！
公開されるのが楽しみです:)

**Comment by amidaku** [comment]
doorkeeper担当の方へ。

告知ご苦労様です。
参加登録しましたが、
 •昼LT
 •メインイベント
 •懇親会
のつながりが弱い感じがしました。
もう少し各イベントの参加申し込みページへの導線を作った方が良いと感じました。

いかがでしょうか。

**Comment by Takashi-U** [comment]
http://matsue-rb.doorkeeper.jp/events/8278

こんな感じにしてみましたがいかがでしょうか？
昼食だけ勝手に変更しましたが、更にアイデアをいただいて内容が固まったら同様に他2つも変更します。よろしくお願いします。

**Comment by amidaku** [comment]
あり〜です。

doorkeeperなので出来る事は限られてますが、このぐらいはやっておいた方が良いですね。
以前自分の勉強会の募集で、懇親会のみ登録して本編の参加申し込みも完了されたと勘違いされるケースが、かなりありましたので、できるだけの事はしておいた方が、良いと思います。

**Comment by sho-h** [comment]
以下のどちらも設定していただいたみたいです。ファイルの読み込みの関係でリダイレクトにしていただいたようです。
- http://regional.rubykaigi.org/matsue05
- http://regional.rubykaigi.org/matrk05

**Comment by yoshiokaCB** [comment]
ありがとうございました！
