### ISSUE TITLE
2013.1.11Matsue.rb定例会時の打ち合わせ時刻について

### ISSUE THREAD

**Issue by Takashi-U** [matsuerb/matrk05#7]
@yoshiokaCB さんへ

Matsue.rbは好きな時間に来て、好きな時間に帰るというスタイルではありますが、時間を合わせた方が都合が付きやすいという方もいらっしゃると思います。

そこでですが、スタッフ遭遇率をアップさせるために、1月の定例会についてスタッフが集まる”目安の時間”というのを設定してはどうかと思うのですが、いかがでしょうか？

重ねてですが、個人的にはMatsue.rbの趣旨が第一だと思いますので、あくまで「いくらか時間に都合がつけられそうだけれど、もしも行くならどの時間帯が一番良いだろうか？」という方々向けと捉えています。

もちろん、ガチの打ち合わせ時刻としても良いでしょうし、趣旨も含めてそういう時間を設定するかご検討くださいませ。よろしくお願いします。

**Comment by amidaku** [comment]
僕は14:00以降が良いです。と、言ってみるテスト

**Comment by yoshiokaCB** [comment]
了解です。
一応前回と同じく15時頃としましょう。
時間は長くても一時間程度で終わりにしましょう。

**Comment by sho-h** [comment]
1/11からはフルで出れそうなので僕はその時間で大丈夫です。:)

**Comment by Takashi-U** [comment]
とりあえずこの件は15時頃目安ということでcloseしたいと思います。事情が変わればまた都度…。
ちなみに、僕はその日愛知に向かっているので不参加です…。
