### ISSUE TITLE
ハッシュタグの確認

### ISSUE THREAD

**Issue by Takashi-U** [matsuerb/matrk05#8]
前回は「#matrk04」でしたので、今回は「#matrk05」かと思います。
これで良いでしょうか？念のため確認です。

**Comment by Takashi-U** [comment]
@yoshiokaCB さんにOK出していただければ良いと、個人的には思っています。

**Comment by sho-h** [comment]
:+1:  > @yoshiokaCB さんにOK

他の過去のものは以下みたいです。
- [#matsuerubykaigi01](http://regional.rubykaigi.org/matsue01)
- [#matrk02](http://regional.rubykaigi.org/matsue02)
- [#matrk03](http://regional.rubykaigi.org/matsue03)
- [#matrk04](http://regional.rubykaigi.org/matsue04)

ただ、04 では OSC とご一緒だったので https://twitter.com/search?q=%23osc12sm を見るに #osc12sm の方しか使われてなかったみたいですw

**Comment by yoshiokaCB** [comment]
OKです！
