### ISSUE TITLE
連絡窓口（メールアドレス等）の確定

### ISSUE THREAD

**Issue by Takashi-U** [matsuerb/matrk05#9]
Webに公開する連絡先を確定させましょう。
- サービス・ツール等の選定（コメント欄にて）
- サービス・ツール等の設定（設定者をassign）
- Web班への伝達（Web班が利用中のIssue https://github.com/tomo-k/matsuerbkaigi05/issues/3 に記入）

で、クローズしましょう。

**Comment by sho-h** [comment]
メールアドレスは過去のお問い合わせを見ると以下みたいでした。
- [matsue01 _at_ rubykaigi.org](http://regional.rubykaigi.org/matsue01)
- [matsue02 _at_ rubykaigi.org](http://regional.rubykaigi.org/matsue02)
- [matsue03 _at_ rubykaigi.org](http://regional.rubykaigi.org/matsue03)
- [matsuerubykaigi04 _at_ googlegroups.com](http://regional.rubykaigi.org/matsue04)

04 では rubykaigi.org じゃない理由が何かあった気がしますが、後でみてみますー。

**Comment by inoh** [comment]
高尾さんはgooglegroupsを前回使ったのが理由と言ってましたけどその関係じゃないですかね？
僕が思ってたのはMatsue.rbのgoogleアカウントを取ってそのアドレスで運用するとかどうかなと思っていました。
アカウントとればアナライズとかもとれますし

**Comment by sho-h** [comment]
確かに作りましたねー。でも前回グループを作った理由が時間の関係だった印象ですね。作ったの8/20だったんですよね。ただ、それ以外の情報は追えなかったのですが...orz

> 僕が思ってたのはMatsue.rbのgoogleアカウントを取ってそのアドレスで運用するとかどうかなと思っていました。
> アカウントとればアナライズとかもとれますし

他の開催でもアドレス取ってる地域はそんなにないみたいですし、公式サイトでも使えるしみたいなところですね。了解です。:)

**Comment by takaokouji** [comment]
地域Ruby会議の運営の方（たぶん角谷さん）に matsue05 at rubykaigi.org を作ってもらい、そのアドレスから転送することになります。なので、転送する先のメールアドレスが必要です。特に問題がなければ matsuerubykaigi05 at googlegroups.com または matrk05 at googlegroups.com でいいかもしれませんね。

**Comment by inoh** [comment]
matsuerubykaigi05 at googlegroups.com で作ってみました。
もしこのアドレスで問題なければメンバへ招待用のメール送ります。

**Comment by takaokouji** [comment]
:+1:

**Comment by sho-h** [comment]
:+1:

**Comment by Takashi-U** [comment]
matsuerubykaigi05 at googlegroups.comを転送先にして利用するのであれば、Reopenするか別にissueを作るかという事で…
